#!/bin/bash

SCRIPTHOME=`pwd`
LN="ln -sfn"

# create symlinks to the executable scripts

$LN "$SCRIPTHOME/web/padmanctl" /usr/local/bin/padmanctl
$LN "$SCRIPTHOME/web/pyophasectl" /usr/local/bin/pyophasectl
$LN "$SCRIPTHOME/web/pyofahrtctl" /usr/local/bin/pyofahrtctl
$LN "$SCRIPTHOME/web/websitectl" /usr/local/bin/websitectl

$LN "$SCRIPTHOME/rootlog/rootlog" /usr/local/bin/rootlog

$LN "$SCRIPTHOME/mail/hrz-whitelist.py" /usr/local/bin/update-mail-stuff

$LN "$SCRIPTHOME/ldap/adduser.py" /usr/local/bin/d120-adduser
$LN "$SCRIPTHOME/ldap/aliasmod.py" /usr/local/bin/d120-aliasmod
$LN "$SCRIPTHOME/ldap/chsh.sh" /usr/local/bin/d120-chsh
$LN "$SCRIPTHOME/ldap/deluser.py" /usr/local/bin/d120-deluser
$LN "$SCRIPTHOME/ldap/groupmod.py" /usr/local/bin/d120-groupmod
