#!/bin/bash

#
# websitectl
#
# Update and manage website deployment.
#

DEPLOYPATH="/srv/djangocms"
DJANGOUSER="djangocms"

function usage {
    cat <<END
Update and manage website deployment.
    update: deploy latest version
    version: show currently installed version
END
}

case "$1" in
    "update")
        cd $DEPLOYPATH && sudo -u $DJANGOUSER script/update --prod
        ;;
    "version")
        cd $DEPLOYPATH && git --no-pager log -1 --format="(%cr) %h %s"
        ;;
    *)
        usage
        ;;
esac
